#@ load("@ytt:data", "data")

apiVersion: v1
kind: Service
metadata:
  name: tanzu-readinessprovider-webhook-service
  namespace: #@ data.values.namespace
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    app: tanzu-readiness-manager
