#@ load("@ytt:data", "data")

apiVersion: v1
kind: Secret
metadata:
  annotations:
    tanzu.vmware.com/readinessprovider-webhook-rotation-interval: 168h
  name: tanzu-readinessprovider-webhook-server-cert
  namespace: #@ data.values.namespace
type: Opaque
